-- MySQL Script generated by MySQL Workbench
-- Wed Mar 19 19:57:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dio_oficina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dio_oficina` ;

-- -----------------------------------------------------
-- Schema dio_oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dio_oficina` DEFAULT CHARACTER SET utf8 ;
USE `dio_oficina` ;

-- -----------------------------------------------------
-- Table `dio_oficina`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Veiculo` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `Marca` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `Ano` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`),
  CONSTRAINT `fk_Veículo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `dio_oficina`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Veículo_Cliente_idx` ON `dio_oficina`.`Veiculo` (`Cliente_idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Mecanico` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idMecanico`, `Veiculo_idVeiculo`, `Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Mecânico_Veículo1`
    FOREIGN KEY (`Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    REFERENCES `dio_oficina`.`Veiculo` (`idVeiculo` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mecânico_Veículo1_idx` ON `dio_oficina`.`Mecanico` (`Veiculo_idVeiculo` ASC, `Veiculo_Cliente_idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Revisao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Revisao` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Revisao` (
  `idRevisao` INT NOT NULL,
  `Data_Revisao` DATE NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  `Mecanico_Veiculo_idVeiculo` INT NOT NULL,
  `Mecanico_Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idRevisao`, `Mecanico_idMecanico`, `Mecanico_Veiculo_idVeiculo`, `Mecanico_Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Revisão_Mecânico1`
    FOREIGN KEY (`Mecanico_idMecanico` , `Mecanico_Veiculo_idVeiculo` , `Mecanico_Veiculo_Cliente_idCliente`)
    REFERENCES `dio_oficina`.`Mecanico` (`idMecanico` , `Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '				';

CREATE INDEX `fk_Revisão_Mecânico1_idx` ON `dio_oficina`.`Revisao` (`Mecanico_idMecanico` ASC, `Mecanico_Veiculo_idVeiculo` ASC, `Mecanico_Veiculo_Cliente_idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Conserto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Conserto` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Conserto` (
  `idConserto` INT NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  `Mecanico_Veiculo_idVeiculo` INT NOT NULL,
  `Mecanico_Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idConserto`, `Mecanico_idMecanico`, `Mecanico_Veiculo_idVeiculo`, `Mecanico_Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Conserto_Mecânico1`
    FOREIGN KEY (`Mecanico_idMecanico` , `Mecanico_Veiculo_idVeiculo` , `Mecanico_Veiculo_Cliente_idCliente`)
    REFERENCES `dio_oficina`.`Mecanico` (`idMecanico` , `Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Conserto_Mecânico1_idx` ON `dio_oficina`.`Conserto` (`Mecanico_idMecanico` ASC, `Mecanico_Veiculo_idVeiculo` ASC, `Mecanico_Veiculo_Cliente_idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Mao_de_Obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Mao_de_Obra` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Mao_de_Obra` (
  `idMao_de_Obra` INT NOT NULL,
  `Valor` FLOAT NULL,
  PRIMARY KEY (`idMao_de_Obra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_oficina`.`OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`OS` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`OS` (
  `idOS` INT NOT NULL,
  `Data_Emissao` DATE NOT NULL,
  `Valor` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Data_Conclusao` DATE NOT NULL,
  PRIMARY KEY (`idOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Conserto_has_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Conserto_has_OS` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Conserto_has_OS` (
  `Conserto_idConserto` INT NOT NULL,
  `Conserto_Mecanico_idMecanico` INT NOT NULL,
  `Conserto_Mecanico_Veiculo_idVeiculo` INT NOT NULL,
  `Conserto_Mecanico_Veiculo_Cliente_idCliente` INT NOT NULL,
  `OS_idOS` INT NOT NULL,
  PRIMARY KEY (`Conserto_idConserto`, `Conserto_Mecanico_idMecanico`, `Conserto_Mecanico_Veiculo_idVeiculo`, `Conserto_Mecanico_Veiculo_Cliente_idCliente`, `OS_idOS`),
  CONSTRAINT `fk_Conserto_has_Ordem de serviço_Conserto1`
    FOREIGN KEY (`Conserto_idConserto` , `Conserto_Mecanico_idMecanico` , `Conserto_Mecanico_Veiculo_idVeiculo` , `Conserto_Mecanico_Veiculo_Cliente_idCliente`)
    REFERENCES `dio_oficina`.`Conserto` (`idConserto` , `Mecanico_idMecanico` , `Mecanico_Veiculo_idVeiculo` , `Mecanico_Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conserto_has_Ordem de serviço_Ordem de serviço1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `dio_oficina`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Conserto_has_Ordem de serviço_Ordem de serviço1_idx` ON `dio_oficina`.`Conserto_has_OS` (`OS_idOS` ASC) VISIBLE;

CREATE INDEX `fk_Conserto_has_Ordem de serviço_Conserto1_idx` ON `dio_oficina`.`Conserto_has_OS` (`Conserto_idConserto` ASC, `Conserto_Mecanico_idMecanico` ASC, `Conserto_Mecanico_Veiculo_idVeiculo` ASC, `Conserto_Mecanico_Veiculo_Cliente_idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Revisao_has_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Revisao_has_OS` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Revisao_has_OS` (
  `Revisao_idRevisao` INT NOT NULL,
  `Revisao_Mecanico_idMecanico` INT NOT NULL,
  `Revisao_Mecanico_Veiculo_idVeiculo` INT NOT NULL,
  `Revisao_Mecanico_Veiculo_Cliente_idCliente` INT NOT NULL,
  `OS_idOS` INT NOT NULL,
  PRIMARY KEY (`Revisao_idRevisao`, `Revisao_Mecanico_idMecanico`, `Revisao_Mecanico_Veiculo_idVeiculo`, `Revisao_Mecanico_Veiculo_Cliente_idCliente`, `OS_idOS`),
  CONSTRAINT `fk_Revisão_has_Ordem de serviço_Revisão1`
    FOREIGN KEY (`Revisao_idRevisao` , `Revisao_Mecanico_idMecanico` , `Revisao_Mecanico_Veiculo_idVeiculo` , `Revisao_Mecanico_Veiculo_Cliente_idCliente`)
    REFERENCES `dio_oficina`.`Revisao` (`idRevisao` , `Mecanico_idMecanico` , `Mecanico_Veiculo_idVeiculo` , `Mecanico_Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Revisão_has_Ordem de serviço_Ordem de serviço1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `dio_oficina`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Revisão_has_Ordem de serviço_Ordem de serviço1_idx` ON `dio_oficina`.`Revisao_has_OS` (`OS_idOS` ASC) VISIBLE;

CREATE INDEX `fk_Revisão_has_Ordem de serviço_Revisão1_idx` ON `dio_oficina`.`Revisao_has_OS` (`Revisao_idRevisao` ASC, `Revisao_Mecanico_idMecanico` ASC, `Revisao_Mecanico_Veiculo_idVeiculo` ASC, `Revisao_Mecanico_Veiculo_Cliente_idCliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Mao_de_Obra_has_Revisao_has_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Mao_de_Obra_has_Revisao_has_OS` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Mao_de_Obra_has_Revisao_has_OS` (
  `Mao_de_Obra_idMao_de_Obra` INT NOT NULL,
  `Revisao_has_OS_Revisao_idRevisao` INT NOT NULL,
  `Revisao_has_OS_Revisao_Mecanico_idMecanico` INT NOT NULL,
  `Revisao_has_OS_Revisao_Mecanico_Veiculo_idVeiculo` INT NOT NULL,
  `Revisao_has_OS_Revisao_Mecanico_Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Mao_de_Obra_idMao_de_Obra`, `Revisao_has_OS_Revisao_idRevisao`, `Revisao_has_OS_Revisao_Mecanico_idMecanico`, `Revisao_has_OS_Revisao_Mecanico_Veiculo_idVeiculo`, `Revisao_has_OS_Revisao_Mecanico_Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Mão de Obra_has_Revisão_has_Ordem de serviço_Mão de Ob1`
    FOREIGN KEY (`Mao_de_Obra_idMao_de_Obra`)
    REFERENCES `dio_oficina`.`Mao_de_Obra` (`idMao_de_Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mão de Obra_has_Revisão_has_Ordem de serviço_Revisão_h1`
    FOREIGN KEY (`Revisao_has_OS_Revisao_idRevisao` , `Revisao_has_OS_Revisao_Mecanico_idMecanico` , `Revisao_has_OS_Revisao_Mecanico_Veiculo_idVeiculo` , `Revisao_has_OS_Revisao_Mecanico_Veiculo_Cliente_idCliente`)
    REFERENCES `dio_oficina`.`Revisao_has_OS` (`Revisao_idRevisao` , `Revisao_Mecanico_idMecanico` , `Revisao_Mecanico_Veiculo_idVeiculo` , `Revisao_Mecanico_Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mão de Obra_has_Revisão_has_Ordem de serviço_Revisão_idx` ON `dio_oficina`.`Mao_de_Obra_has_Revisao_has_OS` (`Revisao_has_OS_Revisao_idRevisao` ASC, `Revisao_has_OS_Revisao_Mecanico_idMecanico` ASC, `Revisao_has_OS_Revisao_Mecanico_Veiculo_idVeiculo` ASC, `Revisao_has_OS_Revisao_Mecanico_Veiculo_Cliente_idCliente` ASC) VISIBLE;

CREATE INDEX `fk_Mão de Obra_has_Revisão_has_Ordem de serviço_Mão de _idx` ON `dio_oficina`.`Mao_de_Obra_has_Revisao_has_OS` (`Mao_de_Obra_idMao_de_Obra` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dio_oficina`.`Mao_de_Obra_has_Conserto_has_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dio_oficina`.`Mao_de_Obra_has_Conserto_has_OS` ;

CREATE TABLE IF NOT EXISTS `dio_oficina`.`Mao_de_Obra_has_Conserto_has_OS` (
  `Mao_de_Obra_idMao_de_Obra` INT NOT NULL,
  `Conserto_has_OS_Conserto_idConserto` INT NOT NULL,
  `Conserto_has_OS_Conserto_Mecanico_idMecanico` INT NOT NULL,
  `Conserto_has_OS_Conserto_Mecanico_Veiculo_idVeiculo` INT NOT NULL,
  `Conserto_has_OS_Conserto_Mecanico_Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Mao_de_Obra_idMao_de_Obra`, `Conserto_has_OS_Conserto_idConserto`, `Conserto_has_OS_Conserto_Mecanico_idMecanico`, `Conserto_has_OS_Conserto_Mecanico_Veiculo_idVeiculo`, `Conserto_has_OS_Conserto_Mecanico_Veiculo_Cliente_idCliente`),
  CONSTRAINT `fk_Mão de Obra_has_Conserto_has_Ordem de serviço_Mão de Ob1`
    FOREIGN KEY (`Mao_de_Obra_idMao_de_Obra`)
    REFERENCES `dio_oficina`.`Mao_de_Obra` (`idMao_de_Obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mão de Obra_has_Conserto_has_Ordem de serviço_Conserto_h1`
    FOREIGN KEY (`Conserto_has_OS_Conserto_idConserto` , `Conserto_has_OS_Conserto_Mecanico_idMecanico` , `Conserto_has_OS_Conserto_Mecanico_Veiculo_idVeiculo` , `Conserto_has_OS_Conserto_Mecanico_Veiculo_Cliente_idCliente`)
    REFERENCES `dio_oficina`.`Conserto_has_OS` (`Conserto_idConserto` , `Conserto_Mecanico_idMecanico` , `Conserto_Mecanico_Veiculo_idVeiculo` , `Conserto_Mecanico_Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mão de Obra_has_Conserto_has_Ordem de serviço_Conserto_idx` ON `dio_oficina`.`Mao_de_Obra_has_Conserto_has_OS` (`Conserto_has_OS_Conserto_idConserto` ASC, `Conserto_has_OS_Conserto_Mecanico_idMecanico` ASC, `Conserto_has_OS_Conserto_Mecanico_Veiculo_idVeiculo` ASC, `Conserto_has_OS_Conserto_Mecanico_Veiculo_Cliente_idCliente` ASC) VISIBLE;

CREATE INDEX `fk_Mão de Obra_has_Conserto_has_Ordem de serviço_Mão de _idx` ON `dio_oficina`.`Mao_de_Obra_has_Conserto_has_OS` (`Mao_de_Obra_idMao_de_Obra` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
